version: '3.8'

services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: pg_db
    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234567890
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d testDB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'

volumes:
  postgres_data:
    name: db-data